import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";

@Injectable({
  providedIn: "root"
})
export class DataService implements InMemoryDbService {
  constructor() {}
  createDb() {
    let student = [
      {
        id: 1,
        first_name: "Tybi",
        last_name: "Antonin",
        email: "tantonin0@ucla.edu",
        gender: "Female",
        full_name: "Tybi Antonin",
        address: "934 Arrowood Point",
        street_number: "39683",
        postal_code: "97232",
        phone: "(503) 2703167",
        country: "United States",
        state: "Oregon",
        city: "Portland",
        university: "Salve Regina University",
        guid: "5c316f99-9e7c-4c2d-bb52-5dcd557f905a",
        date: "12/30/2018",
        skills: "iPhone",
        description:
          "eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit"
      },
      {
        id: 2,
        first_name: "Jamesy",
        last_name: "Spinley",
        email: "jspinley1@time.com",
        gender: "Male",
        full_name: "Jamesy Spinley",
        address: "78 Troy Pass",
        street_number: "31",
        postal_code: "76544",
        phone: "(254) 4972144",
        country: "United States",
        state: "Texas",
        city: "Killeen",
        university: "Keck Graduate Institute of Applied Life Sciences",
        guid: "275c085e-223f-4812-b1ef-73020a3d257d",
        date: "12/31/2018",
        skills: "DHTML",
        description:
          "tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse"
      },
      {
        id: 3,
        first_name: "Freddie",
        last_name: "Stovine",
        email: "fstovine2@bloglovin.com",
        gender: "Female",
        full_name: "Freddie Stovine",
        address: "20 Kenwood Way",
        street_number: "23665",
        postal_code: "02216",
        phone: "(617) 2772043",
        country: "United States",
        state: "Massachusetts",
        city: "Boston",
        university: "American InterContinental University - Atlanta",
        guid: "04f6b2b7-d638-4105-98d6-becc26520798",
        date: "12/26/2018",
        skills: "Xerox Printers",
        description:
          "gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris"
      },
      {
        id: 4,
        first_name: "Celie",
        last_name: "Gritskov",
        email: "cgritskov3@vistaprint.com",
        gender: "Female",
        full_name: "Celie Gritskov",
        address: "291 Ridge Oak Junction",
        street_number: "41723",
        postal_code: "77554",
        phone: "(281) 4431302",
        country: "United States",
        state: "Texas",
        city: "Galveston",
        university: "Francis Marion University",
        guid: "12db2a61-e713-41dd-b490-b1b9c209ddd5",
        date: "4/9/2019",
        skills: "Dbase",
        description:
          "imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam"
      },
      {
        id: 5,
        first_name: "Roberta",
        last_name: "Brach",
        email: "rbrach4@bravesites.com",
        gender: "Female",
        full_name: "Roberta Brach",
        address: "87 Clemons Terrace",
        street_number: "60",
        postal_code: "22234",
        phone: "(571) 6886268",
        country: "United States",
        state: "Virginia",
        city: "Arlington",
        university: "University of North Alabama",
        guid: "fdd37c15-4c2f-47d1-878c-6388507a1024",
        date: "8/14/2018",
        skills: "Olympic Lifting",
        description:
          "at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit"
      },
      {
        id: 6,
        first_name: "Cheryl",
        last_name: "Rickarsey",
        email: "crickarsey5@boston.com",
        gender: "Female",
        full_name: "Cheryl Rickarsey",
        address: "3 Riverside Crossing",
        street_number: "47",
        postal_code: "94913",
        phone: "(415) 2429458",
        country: "United States",
        state: "California",
        city: "San Rafael",
        university: "Berean University of the Assemblies of God",
        guid: "06555661-80d1-4a05-b897-c739908af569",
        date: "2/1/2019",
        skills: "WWII",
        description:
          "elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum"
      },
      {
        id: 7,
        first_name: "Zelma",
        last_name: "Reynoldson",
        email: "zreynoldson6@ed.gov",
        gender: "Female",
        full_name: "Zelma Reynoldson",
        address: "67 Gerald Lane",
        street_number: "12074",
        postal_code: "75185",
        phone: "(972) 6781734",
        country: "United States",
        state: "Texas",
        city: "Mesquite",
        university: "St. John's University",
        guid: "ab3de0fa-5aae-4d94-a8b4-f264aa5a7dd7",
        date: "9/20/2018",
        skills: "Work Very Well with Others",
        description:
          "nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac"
      },
      {
        id: 8,
        first_name: "Tannie",
        last_name: "Sitch",
        email: "tsitch7@illinois.edu",
        gender: "Male",
        full_name: "Tannie Sitch",
        address: "21982 Corben Terrace",
        street_number: "6",
        postal_code: "95150",
        phone: "(408) 2713548",
        country: "United States",
        state: "California",
        city: "San Jose",
        university: "University of Pittsburgh at Greensburg",
        guid: "a12f2615-be67-45aa-91e7-782632efd95b",
        date: "12/16/2018",
        skills: "ICAO",
        description:
          "morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam"
      },
      {
        id: 9,
        first_name: "Livy",
        last_name: "Gillings",
        email: "lgillings8@cbslocal.com",
        gender: "Female",
        full_name: "Livy Gillings",
        address: "1 Sheridan Junction",
        street_number: "138",
        postal_code: "70894",
        phone: "(225) 3795919",
        country: "United States",
        state: "Louisiana",
        city: "Baton Rouge",
        university: "Fisher College",
        guid: "0fe9e27c-bc23-4541-a030-b2cbf10c4879",
        date: "5/11/2018",
        skills: "Awk",
        description:
          "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in"
      },
      {
        id: 10,
        first_name: "Morna",
        last_name: "Tunnacliffe",
        email: "mtunnacliffe9@sciencedaily.com",
        gender: "Female",
        full_name: "Morna Tunnacliffe",
        address: "67 7th Plaza",
        street_number: "1",
        postal_code: "01114",
        phone: "(413) 9370035",
        country: "United States",
        state: "Massachusetts",
        city: "Springfield",
        university: "Black Hills State University",
        guid: "3ba7ff08-32fe-4287-bc0e-009e7232c69f",
        date: "1/21/2019",
        skills: "iHistorian",
        description:
          "sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras"
      },
      {
        id: 11,
        first_name: "Nicolais",
        last_name: "Saltmarshe",
        email: "nsaltmarshea@cdc.gov",
        gender: "Male",
        full_name: "Nicolais Saltmarshe",
        address: "85717 Roxbury Pass",
        street_number: "298",
        postal_code: "33715",
        phone: "(727) 7756258",
        country: "United States",
        state: "Florida",
        city: "Saint Petersburg",
        university: "Gettysburg College",
        guid: "ded149bd-e9b1-49f0-b5ed-3bb0dc0a2bd5",
        date: "6/10/2018",
        skills: "Radio Production",
        description:
          "suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae"
      },
      {
        id: 12,
        first_name: "Inness",
        last_name: "McTerlagh",
        email: "imcterlaghb@linkedin.com",
        gender: "Male",
        full_name: "Inness McTerlagh",
        address: "22649 Florence Place",
        street_number: "600",
        postal_code: "78682",
        phone: "(512) 8603545",
        country: "United States",
        state: "Texas",
        city: "Round Rock",
        university: "United States Air Force Academy",
        guid: "6ca1032e-6797-44a2-ab2e-14fc1da6ebe6",
        date: "9/28/2018",
        skills: "vShield",
        description:
          "vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in"
      },
      {
        id: 13,
        first_name: "Ellerey",
        last_name: "Mourant",
        email: "emourantc@upenn.edu",
        gender: "Male",
        full_name: "Ellerey Mourant",
        address: "32928 Butterfield Trail",
        street_number: "42",
        postal_code: "07544",
        phone: "(862) 9709142",
        country: "United States",
        state: "New Jersey",
        city: "Paterson",
        university: "St. John's College Maryland",
        guid: "2873ef2d-356b-4fd2-a2d4-b23808673009",
        date: "10/2/2018",
        skills: "TCP",
        description:
          "orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam"
      },
      {
        id: 14,
        first_name: "Joby",
        last_name: "Grand",
        email: "jgrandd@craigslist.org",
        gender: "Female",
        full_name: "Joby Grand",
        address: "263 Buhler Street",
        street_number: "538",
        postal_code: "81015",
        phone: "(719) 2528590",
        country: "United States",
        state: "Colorado",
        city: "Pueblo",
        university: "Union College Kentucky",
        guid: "9b2265b2-3b1a-4f34-ae2e-a741d6432180",
        date: "1/12/2019",
        skills: "DC-DC",
        description:
          "integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula"
      },
      {
        id: 15,
        first_name: "Fredric",
        last_name: "Byrcher",
        email: "fbyrchere@bravesites.com",
        gender: "Male",
        full_name: "Fredric Byrcher",
        address: "853 Tony Lane",
        street_number: "4792",
        postal_code: "85045",
        phone: "(602) 1027430",
        country: "United States",
        state: "Arizona",
        city: "Phoenix",
        university: "Valley Forge Christian College",
        guid: "e02469d4-17f7-4764-b56f-186a6a08453f",
        date: "7/13/2018",
        skills: "MCMS",
        description:
          "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis"
      },
      {
        id: 16,
        first_name: "Winnie",
        last_name: "Davisson",
        email: "wdavissonf@flavors.me",
        gender: "Male",
        full_name: "Winnie Davisson",
        address: "192 Chive Street",
        street_number: "96891",
        postal_code: "10705",
        phone: "(914) 4505317",
        country: "United States",
        state: "New York",
        city: "Yonkers",
        university: "St. Norbert College",
        guid: "7df553bd-4069-459b-bb6f-549bb168171f",
        date: "6/23/2018",
        skills: "Rehabilitation Psychology",
        description:
          "sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae"
      },
      {
        id: 17,
        first_name: "Hanni",
        last_name: "Arrighi",
        email: "harrighig@mapy.cz",
        gender: "Female",
        full_name: "Hanni Arrighi",
        address: "10 Arapahoe Lane",
        street_number: "5",
        postal_code: "32885",
        phone: "(407) 9176464",
        country: "United States",
        state: "Florida",
        city: "Orlando",
        university: "Governors State University",
        guid: "5fec1e7e-85a2-45c1-9ec4-7aee64309c29",
        date: "8/11/2018",
        skills: "Training Delivery",
        description:
          "in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas"
      },
      {
        id: 18,
        first_name: "Germain",
        last_name: "De Ortega",
        email: "gdeh@chicagotribune.com",
        gender: "Female",
        full_name: "Germain De Ortega",
        address: "031 Hazelcrest Hill",
        street_number: "47",
        postal_code: "77250",
        phone: "(713) 6345090",
        country: "United States",
        state: "Texas",
        city: "Houston",
        university: "Suffolk University",
        guid: "ee399517-124c-4780-ac7b-1b4e1e58f6d1",
        date: "6/1/2018",
        skills: "Occupational Health",
        description:
          "mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede"
      },
      {
        id: 19,
        first_name: "Marcela",
        last_name: "Pear",
        email: "mpeari@blogtalkradio.com",
        gender: "Female",
        full_name: "Marcela Pear",
        address: "74628 Del Sol Plaza",
        street_number: "346",
        postal_code: "64179",
        phone: "(816) 1277408",
        country: "United States",
        state: "Missouri",
        city: "Kansas City",
        university: "Shaw University",
        guid: "ccec57c9-624d-4809-9846-c801bca06fd5",
        date: "4/2/2019",
        skills: "CCNP",
        description:
          "felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem"
      },
      {
        id: 20,
        first_name: "Nancy",
        last_name: "Guarnier",
        email: "nguarnierj@mac.com",
        gender: "Female",
        full_name: "Nancy Guarnier",
        address: "24 Shopko Avenue",
        street_number: "75",
        postal_code: "11470",
        phone: "(917) 7076002",
        country: "United States",
        state: "New York",
        city: "Jamaica",
        university: "Berne University",
        guid: "68d99eaa-8d98-4a3b-91d7-d4ae4e78af97",
        date: "4/22/2019",
        skills: "Rhapsody",
        description:
          "id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra"
      },
      {
        id: 21,
        first_name: "Phaedra",
        last_name: "Boshers",
        email: "pboshersk@timesonline.co.uk",
        gender: "Female",
        full_name: "Phaedra Boshers",
        address: "9 Victoria Street",
        street_number: "4",
        postal_code: "78715",
        phone: "(512) 8666417",
        country: "United States",
        state: "Texas",
        city: "Austin",
        university:
          "Finch University of Health Sciences - The Chicago Medical School",
        guid: "d3ce296d-4297-42a7-8116-3c08f308c0ff",
        date: "12/8/2018",
        skills: "International HR",
        description:
          "semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus"
      },
      {
        id: 22,
        first_name: "Adriano",
        last_name: "Cheeld",
        email: "acheeldl@free.fr",
        gender: "Male",
        full_name: "Adriano Cheeld",
        address: "51 Havey Pass",
        street_number: "9",
        postal_code: "02283",
        phone: "(617) 4908454",
        country: "United States",
        state: "Massachusetts",
        city: "Boston",
        university: "University of Health Sciences",
        guid: "0a17eaac-d683-4342-8823-d0cdf9a3bca2",
        date: "3/15/2019",
        skills: "Eze Castle",
        description:
          "vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id"
      },
      {
        id: 23,
        first_name: "Ferdinanda",
        last_name: "Pass",
        email: "fpassm@microsoft.com",
        gender: "Female",
        full_name: "Ferdinanda Pass",
        address: "142 Union Drive",
        street_number: "77",
        postal_code: "77080",
        phone: "(281) 7878742",
        country: "United States",
        state: "Texas",
        city: "Houston",
        university: "Pennsylvania State University - Abington",
        guid: "8bf6514e-5d73-4f43-a663-3b302e502706",
        date: "1/10/2019",
        skills: "PL/SQL",
        description:
          "magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis"
      },
      {
        id: 24,
        first_name: "Cecilia",
        last_name: "Hawes",
        email: "chawesn@wsj.com",
        gender: "Female",
        full_name: "Cecilia Hawes",
        address: "12 Ridge Oak Center",
        street_number: "34",
        postal_code: "20551",
        phone: "(202) 6907133",
        country: "United States",
        state: "District of Columbia",
        city: "Washington",
        university: "Louisiana State University at Eunice",
        guid: "44fefd7a-fd31-4a36-b24a-4e3afe2c36cd",
        date: "6/7/2018",
        skills: "Keyboardist",
        description:
          "at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed"
      },
      {
        id: 25,
        first_name: "Nichol",
        last_name: "Gurdon",
        email: "ngurdono@icq.com",
        gender: "Female",
        full_name: "Nichol Gurdon",
        address: "2842 Glacier Hill Hill",
        street_number: "08136",
        postal_code: "33185",
        phone: "(305) 8115235",
        country: "United States",
        state: "Florida",
        city: "Miami",
        university: "Northwest Nazarene University",
        guid: "ce883989-40f8-47d9-890a-d891fafb1a73",
        date: "2/12/2019",
        skills: "Jingles",
        description:
          "id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est"
      }
    ];

    return { student };
  }
}
